# netlify.toml
# Configuration for Netlify deploys

[build]
  publish = "."       # Serve files from the root (index.html, etc.)
  command = ""        # No build step needed for plain HTML/CSS/JS

# Redirect www to root
[[redirects]]
  from = "http://canyonlandtech.com/*"
  to = "https://www.canyonlandtech.com/:splat"
  status = 301
  force = true
